spring:
  datasource:
    url:  jdbc:mysql://192.168.2.200/jdbc_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: root
      password: new.1234
      max-lifetime: 1765000
      maximum-pool-size: 15
      minimum-idle: 2
      connection-timeout: 1765000
mybatis:
    type-aliases-package: com.avcdata.model
    mapper-locations: classpath:mapper/*.xml
    configuration:
      call-setters-on-nulls: true
      map-underscore-to-camel-case: true
mapper:
    #通用Mapper目录
    mappers:
        - com.avcdata.util.MyMapper
    not-empty: false
    identity: MYSQL
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
logging:
  # 日志打印级别配置
  config: classpath:logback.xml